<?php
/**
 *  Created by www.kuleiman.com.
 *  User: YaoHongQiang
 *  Date: 2021/6/2   14:52
 *  description:
 */

namespace app\home\controller;


use app\home\HomeBase;
use think\facade\View;

class xml extends HomeBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    function index(){
        $open_animation_data=[
            'type'=>1,
            'time'=>5,
        ];
        View::config(['view_suffix' => 'xml']);
        View::assign('open_animation_data',json_encode($open_animation_data));
        return View::fetch();
    }
}